"""The strategy verdict, served exactly as it was generated.

Read-only by construction: the endpoint takes no parameters, so nothing a caller
sends can change a verdict, and there is no write path. The artifact's embedded
content hash is verified on every read; an artifact edited after generation is
refused with a 500 rather than served — a verdict that cannot be trusted is
worse than no verdict.

The artifact is regenerated by scripts/generate_strategy_verdict.py and ships
with the image, like research_record.py; docs/ is not in the image, so the full
report is referenced by its repository path.
"""

import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException

from app.core.verdict import StrategyVerdict
from app.schemas.strategy_verdict import StrategyVerdictResponse

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/strategy-verdict", tags=["strategy-verdict"])

ARTIFACT = Path(__file__).resolve().parents[2] / "core" / "verdict_artifacts" / "momentum_v1.0.verdict.json"
REPORT_PATH = "docs/audit/momentum_v1.0/momentum_v1.0_audit_closure.md"


@router.get("", response_model=StrategyVerdictResponse)
def strategy_verdict() -> StrategyVerdictResponse:
    try:
        verdict = StrategyVerdict.from_json(ARTIFACT.read_text())
    except (OSError, ValueError, TypeError) as exc:
        logger.error("strategy_verdict.unservable path=%s error=%s", ARTIFACT, exc)
        raise HTTPException(status_code=500, detail="The strategy verdict failed its integrity check and is not served.")

    ev = verdict.evidence
    suite = ev["test_run"]["suite"]
    return StrategyVerdictResponse(
        strategy_id=verdict.strategy_id,
        strategy_version=verdict.strategy_version,
        measurement_verdict=verdict.measurement_verdict,
        edge_verdict=verdict.edge_verdict,
        promotion_verdict=verdict.promotion_verdict,
        generated_at=verdict.generated_at,
        code_revision=verdict.code_revision,
        data_snapshot=verdict.data_snapshot,
        content_sha256=verdict.content_sha256(),
        summary=verdict.summary,
        measurement_checks=ev["measurement_checks"],
        edge_checks=ev["edge_checks"],
        governance_checks=ev["governance_checks"],
        edge_figures=ev["edge_figures"],
        thresholds=ev["thresholds"],
        known_biases=ev["known_biases"],
        test_suite={k: suite[k] for k in ("tests", "passed", "failures", "errors", "skipped", "xfailed")}
        | {"excluded": suite.get("excluded", [])},
        live_signals_through=ev.get("live_signals_through"),
        report_path=REPORT_PATH,
    )
