"""Add forward testing models

Revision ID: 0ae582190d5d
Revises: 4608ed4094db
Create Date: 2026-08-16 13:28:33.524435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae582190d5d'
down_revision: Union[str, None] = '4608ed4094db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cumulative_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('drawdown', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_equity_snapshots_date'), 'paper_equity_snapshots', ['date'], unique=False)
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('return_1d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_5d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_10d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_favorable_excursion', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_adverse_excursion', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('target_hit', sa.Boolean(), nullable=False),
    sa.Column('stop_hit', sa.Boolean(), nullable=False),
    sa.Column('nifty_return_1d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_5d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_10d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['daily_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_outcomes')
    op.drop_index(op.f('ix_paper_equity_snapshots_date'), table_name='paper_equity_snapshots')
    op.drop_table('paper_equity_snapshots')
    # ### end Alembic commands ###
