"""add pipeline_runs table

Revision ID: 4608ed4094db
Revises: f6a24d0b8e13
Create Date: 2026-08-15 22:41:48.871618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4608ed4094db'
down_revision: Union[str, None] = 'f6a24d0b8e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stocks_requested', sa.Integer(), nullable=False),
    sa.Column('stocks_succeeded', sa.Integer(), nullable=False),
    sa.Column('stocks_failed', sa.Integer(), nullable=False),
    sa.Column('failed_symbols', sa.JSON(), nullable=True),
    sa.Column('failure_details', sa.JSON(), nullable=True),
    sa.Column('signals_generated', sa.Boolean(), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_run_date'), 'pipeline_runs', ['run_date'], unique=False)
    op.drop_constraint('nse_symbols_symbol_key', 'nse_symbols', type_='unique')
    op.drop_index('ix_nse_symbols_symbol', table_name='nse_symbols')
    op.create_index(op.f('ix_nse_symbols_symbol'), 'nse_symbols', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nse_symbols_symbol'), table_name='nse_symbols')
    op.create_index('ix_nse_symbols_symbol', 'nse_symbols', ['symbol'], unique=False)
    op.create_unique_constraint('nse_symbols_symbol_key', 'nse_symbols', ['symbol'])
    op.drop_index(op.f('ix_pipeline_runs_run_date'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
