"""add stop_method to recommendations

Revision ID: 848a4f16fba8
Revises: 8d14cb1d845f
Create Date: 2026-08-14 08:23:40.940666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848a4f16fba8'
down_revision: Union[str, None] = '8d14cb1d845f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('stop_method', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'stop_method')
    # ### end Alembic commands ###
