"""add missing_inputs to recommendations

Revision ID: 8d14cb1d845f
Revises: c818120f2460
Create Date: 2026-08-14 08:16:29.538878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d14cb1d845f'
down_revision: Union[str, None] = 'c818120f2460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('missing_inputs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'missing_inputs')
    # ### end Alembic commands ###
