"""Strategy verdicts: generated by code from explicit checks, never written by hand.

A verdict answers three separate questions, in order, and each answer gates the
next:

1. MEASUREMENT — can the numbers be trusted at all? Data, execution simulation,
   metrics, reproducibility.
2. EDGE — given trustworthy numbers, does the strategy beat what it must beat,
   after costs, robustly?
3. PROMOTION — given an edge, may it be put in front of anyone as more than
   research? That also needs governance a backtest cannot supply.

Why the gating is strict. An edge verdict computed on numbers the measurement
checks could not vouch for is not a weak verdict, it is no verdict: a defect in
the execution simulation can move a result in either direction. So measurement
anything-but-PASS makes edge BLOCKED, not FAIL, even when every edge check that
could be evaluated fails. The edge checks are still computed and published in
the evidence, so a BLOCKED never hides what they showed.

Nothing in this module reads prose, a flag file, or a UI setting. The three
verdicts are pure functions of the check statuses, and the check statuses are
produced by services/strategy_verdict.py from test outcomes and committed
evidence. There is deliberately no parameter anywhere that sets a verdict
directly.
"""

import json
from dataclasses import asdict, dataclass, field
from typing import Any

from app.core.canonical import canonical_json_bytes, sha256_hex, to_canonical

# --- controlled vocabularies ---------------------------------------------------
MEASUREMENT_VALUES = ("PASS", "FAIL", "BLOCKED")
EDGE_VALUES = ("PASS", "FAIL", "INCONCLUSIVE", "BLOCKED")
PROMOTION_VALUES = ("APPROVED", "BLOCKED", "DEFERRED")

# A single check. NOT_EVALUATED is not a soft FAIL and not a soft PASS: it means
# no admissible evidence exists for it. How much that matters depends on the
# group — see decide_*.
CHECK_STATUSES = ("PASS", "FAIL", "NOT_EVALUATED")


@dataclass(frozen=True)
class Check:
    name: str
    status: str
    required: bool
    detail: str
    # Test node ids, or dotted keys into the evidence bundle, that produced it.
    evidence: tuple[str, ...] = ()

    def __post_init__(self):
        if self.status not in CHECK_STATUSES:
            raise ValueError(f"check {self.name!r}: status {self.status!r} not in {CHECK_STATUSES}")
        if not self.detail:
            raise ValueError(f"check {self.name!r}: a check without a stated reason is not auditable")


def decide_measurement(checks: list[Check]) -> str:
    required = [c for c in checks if c.required]
    if not required:
        # An empty check list would otherwise fall through to PASS.
        return "BLOCKED"
    if any(c.status == "FAIL" for c in required):
        return "FAIL"
    if any(c.status == "NOT_EVALUATED" for c in required):
        return "BLOCKED"
    return "PASS"


def decide_edge(checks: list[Check], measurement: str) -> str:
    if measurement not in MEASUREMENT_VALUES:
        raise ValueError(f"measurement verdict {measurement!r} not in {MEASUREMENT_VALUES}")
    if measurement != "PASS":
        return "BLOCKED"
    required = [c for c in checks if c.required]
    if not required:
        return "INCONCLUSIVE"
    if any(c.status == "FAIL" for c in required):
        return "FAIL"
    # Nothing failed, but something could not be evaluated: an edge is not
    # established by the checks that happened to have evidence.
    if any(c.status == "NOT_EVALUATED" for c in required):
        return "INCONCLUSIVE"
    return "PASS"


def decide_promotion(measurement: str, edge: str, governance: list[Check]) -> str:
    if edge not in EDGE_VALUES:
        raise ValueError(f"edge verdict {edge!r} not in {EDGE_VALUES}")
    # A failed or unmeasurable strategy is blocked outright: no amount of
    # governance paperwork promotes it.
    if measurement != "PASS" or edge in ("FAIL", "BLOCKED"):
        return "BLOCKED"
    if edge == "INCONCLUSIVE":
        return "DEFERRED"
    # Edge PASS. Still only DEFERRED until every governance check is PASS —
    # data terms, scope, regulatory review are not things a backtest settles.
    if governance and all(c.status == "PASS" for c in governance):
        return "APPROVED"
    return "DEFERRED"


def build_summary(measurement: str, edge: str, promotion: str,
                  measurement_checks: list[Check], edge_checks: list[Check],
                  governance: list[Check]) -> str:
    """Plain-English summary, generated from the same checks as the verdict so
    the two cannot disagree. No free text enters here."""
    def names(checks, status):
        return [c.name for c in checks if c.required and c.status == status]

    parts: list[str] = []

    failed_m, missing_m = names(measurement_checks, "FAIL"), names(measurement_checks, "NOT_EVALUATED")
    if measurement == "PASS":
        parts.append(f"Measurement PASS: all {sum(c.required for c in measurement_checks)} "
                     f"required validity checks passed.")
    elif measurement == "FAIL":
        parts.append(f"Measurement FAIL: {len(failed_m)} required validity check(s) failed "
                     f"({', '.join(failed_m)}).")
    else:
        parts.append(f"Measurement BLOCKED: {len(missing_m)} required validity check(s) could "
                     f"not be evaluated ({', '.join(missing_m)}).")

    failed_e, missing_e = names(edge_checks, "FAIL"), names(edge_checks, "NOT_EVALUATED")
    passed_e = names(edge_checks, "PASS")
    evaluated = len(failed_e) + len(passed_e)
    if edge == "BLOCKED":
        parts.append(
            f"Edge BLOCKED: not judged while measurement is {measurement}. Of the "
            f"{evaluated} required edge check(s) that could be evaluated, {len(failed_e)} fail"
            + (f" ({', '.join(failed_e)})" if failed_e else "") + "."
        )
    elif edge == "FAIL":
        parts.append(f"Edge FAIL: {len(failed_e)} required edge check(s) failed ({', '.join(failed_e)}).")
    elif edge == "INCONCLUSIVE":
        parts.append(f"Edge INCONCLUSIVE: no required check failed, but {len(missing_e)} could not "
                     f"be evaluated ({', '.join(missing_e)}).")
    else:
        parts.append("Edge PASS: every required edge check passed.")

    if promotion == "BLOCKED":
        parts.append("Promotion BLOCKED.")
    elif promotion == "DEFERRED":
        pending = [c.name for c in governance if c.status != "PASS"]
        parts.append("Promotion DEFERRED" + (f": pending {', '.join(pending)}." if pending else "."))
    else:
        parts.append("Promotion APPROVED.")
    return " ".join(parts)


@dataclass(frozen=True)
class StrategyVerdict:
    strategy_id: str
    # The exact frozen strategy identifier from core/v1_strategy.py. Pinned so a
    # change to the strategy invalidates this verdict rather than silently
    # inheriting it — a test compares the two.
    strategy_version: str
    measurement_verdict: str
    edge_verdict: str
    promotion_verdict: str
    generated_at: str
    code_revision: str
    data_snapshot: str
    summary: str
    evidence: dict = field(default_factory=dict)

    def __post_init__(self):
        for name, value, allowed in (
            ("measurement_verdict", self.measurement_verdict, MEASUREMENT_VALUES),
            ("edge_verdict", self.edge_verdict, EDGE_VALUES),
            ("promotion_verdict", self.promotion_verdict, PROMOTION_VALUES),
        ):
            if value not in allowed:
                raise ValueError(f"{name}={value!r} not in {allowed}")
        for name in ("strategy_id", "strategy_version", "code_revision", "data_snapshot", "summary"):
            if not getattr(self, name):
                raise ValueError(f"{name} must not be empty")
        # The gating is an invariant of the object, not just of the functions
        # that usually build it: a hand-assembled verdict cannot claim an edge
        # on unvalidated measurement or a promotion over a failed edge.
        if self.measurement_verdict != "PASS" and self.edge_verdict != "BLOCKED":
            raise ValueError("edge must be BLOCKED unless measurement is PASS")
        if self.promotion_verdict == "APPROVED" and self.edge_verdict != "PASS":
            raise ValueError("promotion cannot be APPROVED without an edge PASS")

    def content(self) -> dict:
        """Everything except generated_at. Two generations from identical
        inputs differ only in when they ran, so the hash must not include it."""
        payload = asdict(self)
        payload.pop("generated_at")
        return to_canonical(payload)

    def content_sha256(self) -> str:
        return sha256_hex(self.content())

    def to_json(self) -> str:
        """Readable artifact form: sorted keys, indented, content hash embedded."""
        payload = to_canonical(asdict(self))
        payload["content_sha256"] = self.content_sha256()
        return json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False, allow_nan=False) + "\n"

    @classmethod
    def from_json(cls, text: str) -> "StrategyVerdict":
        payload: dict[str, Any] = json.loads(text)
        stored_hash = payload.pop("content_sha256", None)
        verdict = cls(**payload)
        if stored_hash is not None and stored_hash != verdict.content_sha256():
            raise ValueError(
                f"verdict content hash mismatch: stored {stored_hash}, computed "
                f"{verdict.content_sha256()} — the artifact was edited after generation"
            )
        return verdict


def canonical_verdict_bytes(verdict: StrategyVerdict) -> bytes:
    return canonical_json_bytes(verdict.content())
